version: '3'
services:
  flask-sample:
    build: .
    depends_on:
      - db
    ports:
     - "5000:5000"
    environment:
     - DBUSER=postgres
     - DBPASS=changeme
     - DBHOST=db
     - DBNAME=postgres
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_URL : 127.0.0.1:5432
      POSTGRES_USER : postgres
      POSTGRES_PW : dbpw
      POSTGRES_DB : test