version: '3'

services:
  web:
    build:
    context: .
    dockerfile: DockerFile
    ports:
      - "80:80"
    volumes:
      - ./myapp:/myapp
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
  #SQLAlchemy:
